[package]
name = "adbear"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
fast_qr = "0.12.5"
mdns-sd = { version = "0.11.4", default-features = false, features = ["async"] }
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "time"] }
